a = input()
replace1 = a.replace("c=","@")
replace2 = replace1.replace("c-","@")
replace3 = replace2.replace("dz=","@")
replace4 = replace3.replace("d-","@")
replace5 = replace4.replace("lj","@")
replace6 = replace5.replace("nj","@")
replace7 = replace6.replace("s=","@")
replace8 = replace7.replace("z=","@")
print(len(replace8))